version: '2'
services:
        php:
                build: .
                ports:
                        - 8000:80
                        - 8080:8080
                volumes:
                        - ./laravel:/app
